#!/usr/bin/env bash
### dai-join -- buy SKR for gems
### Usage: dai join <amount-in-skr>
set -e
[ $# = 1 ] || dai join --usage
jam=$(dai wad -h "$1")
echo >&2 "Generating $jam SKR depositing GEM..."
jam=$(dai wad "$1")
(set -x; seth send "${DAI_TUB?}" "join(uint256)" "$jam")
