#!/usr/bin/env bash
### dai-open -- create a new cup (collateralized debt position)
set -e
echo >&2 "Opening cup..."
tx=$(seth send --async "${DAI_TUB?}" "open()(bytes32)")
echo >&2 -n "Waiting for transaction receipt..."
number=$(SETH_TICK=true seth receipt "$tx" blockNumber)
number=$(seth --to-hex "$number")
echo >&2
logs=$(seth rpc eth_getLogs -- -n {} -s "${DAI_TUB?}" -i address \
                                 -s "$number"  -i fromBlock \
                                 -s "$number"  -i toBlock \
                                   -n [] -s "$(seth keccak "$(seth --from-ascii 'LogNewCup(address,bytes32)')")" -i append \
                                         -s "0x$(seth --to-uint256 "${ETH_FROM?}")" -i append \
                                   -i topics \
                           -i append \
  | echo "[$(paste -sd , -)]")
data=$(echo "$logs" | jshon -a -e data -u)
hash=$(echo "$logs" | jshon -a -e transactionHash -u)
id=$(seth --to-dec "$data")
[ "$hash" == "$tx" ] && echo "Opened cup $id"
